// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdGD-D7_gBtkb5T1aJcn74B5NmtZ_O9gw',
    appId: '1:581244823119:web:513c9b7398dce07194ec3a',
    messagingSenderId: '581244823119',
    projectId: 'to-do-note-31b8a',
    authDomain: 'to-do-note-31b8a.firebaseapp.com',
    storageBucket: 'to-do-note-31b8a.appspot.com',
    measurementId: 'G-6F760K733P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrzBjkDoCQ3Au5tHsRWMKrzYfhtkSY_WQ',
    appId: '1:581244823119:android:f14b2bb05a6c5edb94ec3a',
    messagingSenderId: '581244823119',
    projectId: 'to-do-note-31b8a',
    storageBucket: 'to-do-note-31b8a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDq2haspaUScQj2ZWuastT-vKk8qgb0Xe0',
    appId: '1:581244823119:ios:d8e9fc560f95b7c194ec3a',
    messagingSenderId: '581244823119',
    projectId: 'to-do-note-31b8a',
    storageBucket: 'to-do-note-31b8a.appspot.com',
    iosBundleId: 'com.example.toDoNote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDq2haspaUScQj2ZWuastT-vKk8qgb0Xe0',
    appId: '1:581244823119:ios:8627587eac0bc33194ec3a',
    messagingSenderId: '581244823119',
    projectId: 'to-do-note-31b8a',
    storageBucket: 'to-do-note-31b8a.appspot.com',
    iosBundleId: 'com.example.toDoNote.RunnerTests',
  );
}
